// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6L6xsItnMS-5_Zm-WtzlUo_MrdbRMEBw',
    appId: '1:62682007036:web:14a1f48d2f05095859de79',
    messagingSenderId: '62682007036',
    projectId: 'safebites-huzaifa',
    authDomain: 'safebites-huzaifa.firebaseapp.com',
    storageBucket: 'safebites-huzaifa.appspot.com',
    measurementId: 'G-6ZNRFD3ZG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6CyKdZGQ8rH3mY3p4cQw8krpywbi9RII',
    appId: '1:62682007036:android:b1018fee26ca9c6159de79',
    messagingSenderId: '62682007036',
    projectId: 'safebites-huzaifa',
    storageBucket: 'safebites-huzaifa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrd96z1fVS8C7M9houvK68DLT6R1-TMf8',
    appId: '1:62682007036:ios:b5757ffd727c107d59de79',
    messagingSenderId: '62682007036',
    projectId: 'safebites-huzaifa',
    storageBucket: 'safebites-huzaifa.appspot.com',
    iosClientId: '62682007036-u2ksvrim8g0ksias8gfd79pqs20onm4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.safebites',
  );
}
